language: java
sudo: required
install: true
script: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
dist: trusty
jdk:
  - openjdk8

notification:
  email:
    - zhangjian12424@gmail.com
  on_success: never
  on_failure: always

services:
  - docker
after_success:
  - docker build -t helixcs/rmt . --build-arg PORT=8080 --build-arg JVM_PARMS="-Xms512m -Xmx512m -Xmn256m"
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push helixcs/rmt:latest

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: RELEASE/rmt-app.jar
  skip_cleanup: true
  on:
    tags: true