language: java
install: true
script: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
dist: trusty
jdk:
  - oraclejdk8
  - openjdk8

notification:
  email:
    - zhangjian12424@gmail.com
  on_success: never
  on_failure: always
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: RELEASE/*
  skip_cleanup: true
  on:
    tags: true